# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import azure_embedded_speech_pb2 as azure__embedded__speech__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in azure_embedded_speech_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AzureEmbeddedSpeechStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recognize = channel.stream_stream(
                '/voice_agent.azure_embedded.v1.AzureEmbeddedSpeech/Recognize',
                request_serializer=azure__embedded__speech__pb2.AsrRequest.SerializeToString,
                response_deserializer=azure__embedded__speech__pb2.AsrEvent.FromString,
                _registered_method=True)
        self.Synthesize = channel.unary_unary(
                '/voice_agent.azure_embedded.v1.AzureEmbeddedSpeech/Synthesize',
                request_serializer=azure__embedded__speech__pb2.TtsRequest.SerializeToString,
                response_deserializer=azure__embedded__speech__pb2.TtsResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/voice_agent.azure_embedded.v1.AzureEmbeddedSpeech/Health',
                request_serializer=azure__embedded__speech__pb2.HealthRequest.SerializeToString,
                response_deserializer=azure__embedded__speech__pb2.HealthResponse.FromString,
                _registered_method=True)


class AzureEmbeddedSpeechServicer:
    """Missing associated documentation comment in .proto file."""

    def Recognize(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Synthesize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AzureEmbeddedSpeechServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recognize': grpc.stream_stream_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=azure__embedded__speech__pb2.AsrRequest.FromString,
                    response_serializer=azure__embedded__speech__pb2.AsrEvent.SerializeToString,
            ),
            'Synthesize': grpc.unary_unary_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=azure__embedded__speech__pb2.TtsRequest.FromString,
                    response_serializer=azure__embedded__speech__pb2.TtsResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=azure__embedded__speech__pb2.HealthRequest.FromString,
                    response_serializer=azure__embedded__speech__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voice_agent.azure_embedded.v1.AzureEmbeddedSpeech', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voice_agent.azure_embedded.v1.AzureEmbeddedSpeech', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AzureEmbeddedSpeech:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Recognize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/voice_agent.azure_embedded.v1.AzureEmbeddedSpeech/Recognize',
            azure__embedded__speech__pb2.AsrRequest.SerializeToString,
            azure__embedded__speech__pb2.AsrEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voice_agent.azure_embedded.v1.AzureEmbeddedSpeech/Synthesize',
            azure__embedded__speech__pb2.TtsRequest.SerializeToString,
            azure__embedded__speech__pb2.TtsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voice_agent.azure_embedded.v1.AzureEmbeddedSpeech/Health',
            azure__embedded__speech__pb2.HealthRequest.SerializeToString,
            azure__embedded__speech__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
